language: objective-c
osx_image: xcode7
sudo: false
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  matrix:
    - DESTINATION="OS=8.1,name=iPhone 4S" SCHEME="AFNetworking iOS" SDK=iphonesimulator9.0 BUILD_EXAMPLE="YES" POD_LINT="YES" EXAMPLE_SCHEME="iOS Example"
    - DESTINATION="OS=8.2,name=iPhone 5" SCHEME="AFNetworking iOS" SDK=iphonesimulator9.0 BUILD_EXAMPLE="YES" POD_LINT="NO" EXAMPLE_SCHEME="iOS Example"
    - DESTINATION="OS=8.3,name=iPhone 5S" SCHEME="AFNetworking iOS" SDK=iphonesimulator9.0 BUILD_EXAMPLE="YES" POD_LINT="NO" EXAMPLE_SCHEME="iOS Example"
    - DESTINATION="OS=8.4,name=iPhone 6" SCHEME="AFNetworking iOS" SDK=iphonesimulator9.0 BUILD_EXAMPLE="YES" POD_LINT="NO" EXAMPLE_SCHEME="iOS Example"
    - DESTINATION="OS=9.0,name=iPhone 6 Plus" SCHEME="AFNetworking iOS" SDK=iphonesimulator9.0 BUILD_EXAMPLE="YES" POD_LINT="NO" EXAMPLE_SCHEME="iOS Example"
    - DESTINATION="arch=x86_64" SCHEME="AFNetworking OS X" SDK=macosx10.11 BUILD_EXAMPLE="NO" POD_LINT="NO" EXAMPLE_SCHEME="OS X Example"
before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -project AFNetworking.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" 
    -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
  - xcodebuild -project AFNetworking.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" 
    -configuration Release ONLY_ACTIVE_ARCH=NO test | xcpretty -c
  - if [ $BUILD_EXAMPLE == "YES" ]; then 
      xcodebuild -workspace AFNetworking.xcworkspace -scheme "$EXAMPLE_SCHEME" -destination "$DESTINATION" 
      -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c; 
    fi
  - if [ $BUILD_EXAMPLE == "YES" ]; then 
      xcodebuild -workspace AFNetworking.xcworkspace -scheme "$EXAMPLE_SCHEME" -destination "$DESTINATION" 
      -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty -c; 
    fi
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint --quick;
    fi
